### ISSUE TITLE
Python 3.8 errors 

### ISSUE THREAD

**Issue by Kelvinrr** [DOI-USGS/SpiceQL#23]
When trying to use python 3.8 with spiceql, it builds fine but fails on import: 

```python
>>> import pyspiceql
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/krodriguez/repos/SpiceQL/build/bindings/python/pyspiceql/__init__.py", line 1, in <module>
    from .pyspiceql import *
  File "/Users/krodriguez/repos/SpiceQL/build/bindings/python/pyspiceql/pyspiceql.py", line 13, in <module>
    from . import _pyspiceql
ImportError: dlopen(/Users/krodriguez/repos/SpiceQL/build/bindings/python/pyspiceql/_pyspiceql.so, 0x0002): symbol not found in flat namespace '_PyCMethod_New'
```

## Possible Solution

This might be due to how SWIG is wrapping parts of SpiceQL and there is some missing capability in python 3.8. We support 3.8 in our other packages so it might be important to see if we can figure out a workaround for this. 

Otherwise we simply wont support it as it seems the symbol is missing from 3.8: https://github.com/PyO3/pyo3/discussions/3376

**Comment by Kelvinrr** [comment]
3.8 and 2.9 dropped from CI
